In [1]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.linear_model import LinearRegression
import pandas as pd

In [2]:
print("Hello")

Hello


In [3]:
array = ['A','B','C','A','B','C','A','B','C','A','B','C']
le = LabelEncoder()
oe = OneHotEncoder()
le = le.fit_transform(array)
oe = oe.fit_transform([le]).toarray()


/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [4]:
print(le)

[0 1 2 0 1 2 0 1 2 0 1 2]


In [5]:
print(oe)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [6]:
"""
Reading data now
"""
print("Application on data")

Application on data


In [7]:
data = pd.read_csv('data2.csv').values
X = data[:,:-1]
Y = data[:,4]
print(X, Y)

[['Development' 2300 0 1.1]
 ['Testing' 2100 1 1.3]
 ['Development' 2104 2 1.5]
 ['UX Designer' 1200 1 2.0]
 ['Testing' 1254 2 2.2]
 ['UX Designer' 1236 1 2.9]
 ['Development' 1452 2 3.0]
 ['Testing' 1789 1 3.2]
 ['UX Designer' 1645 1 3.2]
 ['UX Designer' 1258 0 3.7]
 ['Testing' 1478 3 3.9]
 ['Development' 1257 2 4.0]
 ['Development' 1596 1 4.0]
 ['Testing' 1256 2 4.1]
 ['UX Designer' 1489 3 4.5]
 ['Development' 1236 3 4.9]
 ['Testing' 2311 2 5.1]
 ['UX Designer' 2245 3 5.3]
 ['Development' 2365 1 5.9]
 ['Development' 1500 3 6.0]
 ['Testing' 1456 2 6.8]
 ['Testing' 1760 1 7.1]
 ['UX Designer' 2400 4 7.9]
 ['Development' 2148 3 8.2]
 ['UX Designer' 1450 2 8.7]
 ['UX Designer' 1000 4 9.0]
 ['Testing' 1540 3 9.5]
 ['Development' 1500 2 9.6]
 ['Testing' 3000 4 10.3]
 ['UX Designer' 2100 3 10.5]] [39343 46205 37731 43525 39891 56642 60150 54445 64445 57189 63218 55794
 56957 57081 61111 67938 66029 83088 81363 93940 91738 98273 101302 113812
 109431 105582 116969 112635 122391 121872]


In [8]:
le = LabelEncoder()
X[:,0] = le.fit_transform(X[:,0])
print(X)
oh = OneHotEncoder(categorical_features=[0])
X = oh.fit_transform(X).toarray()
print(X)

[[0 2300 0 1.1]
 [1 2100 1 1.3]
 [0 2104 2 1.5]
 [2 1200 1 2.0]
 [1 1254 2 2.2]
 [2 1236 1 2.9]
 [0 1452 2 3.0]
 [1 1789 1 3.2]
 [2 1645 1 3.2]
 [2 1258 0 3.7]
 [1 1478 3 3.9]
 [0 1257 2 4.0]
 [0 1596 1 4.0]
 [1 1256 2 4.1]
 [2 1489 3 4.5]
 [0 1236 3 4.9]
 [1 2311 2 5.1]
 [2 2245 3 5.3]
 [0 2365 1 5.9]
 [0 1500 3 6.0]
 [1 1456 2 6.8]
 [1 1760 1 7.1]
 [2 2400 4 7.9]
 [0 2148 3 8.2]
 [2 1450 2 8.7]
 [2 1000 4 9.0]
 [1 1540 3 9.5]
 [0 1500 2 9.6]
 [1 3000 4 10.3]
 [2 2100 3 10.5]]
[[1.000e+00 0.000e+00 0.000e+00 2.300e+03 0.000e+00 1.100e+00]
 [0.000e+00 1.000e+00 0.000e+00 2.100e+03 1.000e+00 1.300e+00]
 [1.000e+00 0.000e+00 0.000e+00 2.104e+03 2.000e+00 1.500e+00]
 [0.000e+00 0.000e+00 1.000e+00 1.200e+03 1.000e+00 2.000e+00]
 [0.000e+00 1.000e+00 0.000e+00 1.254e+03 2.000e+00 2.200e+00]
 [0.000e+00 0.000e+00 1.000e+00 1.236e+03 1.000e+00 2.900e+00]
 [1.000e+00 0.000e+00 0.000e+00 1.452e+03 2.000e+00 3.000e+00]
 [0.000e+00 1.000e+00 0.000e+00 1.789e+03 1.000e+00 3.200e+00]
 [0.000e+00 0

/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [9]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

X = X[:,1:]
print(X)

[[0.000e+00 0.000e+00 2.300e+03 0.000e+00 1.100e+00]
 [1.000e+00 0.000e+00 2.100e+03 1.000e+00 1.300e+00]
 [0.000e+00 0.000e+00 2.104e+03 2.000e+00 1.500e+00]
 [0.000e+00 1.000e+00 1.200e+03 1.000e+00 2.000e+00]
 [1.000e+00 0.000e+00 1.254e+03 2.000e+00 2.200e+00]
 [0.000e+00 1.000e+00 1.236e+03 1.000e+00 2.900e+00]
 [0.000e+00 0.000e+00 1.452e+03 2.000e+00 3.000e+00]
 [1.000e+00 0.000e+00 1.789e+03 1.000e+00 3.200e+00]
 [0.000e+00 1.000e+00 1.645e+03 1.000e+00 3.200e+00]
 [0.000e+00 1.000e+00 1.258e+03 0.000e+00 3.700e+00]
 [1.000e+00 0.000e+00 1.478e+03 3.000e+00 3.900e+00]
 [0.000e+00 0.000e+00 1.257e+03 2.000e+00 4.000e+00]
 [0.000e+00 0.000e+00 1.596e+03 1.000e+00 4.000e+00]
 [1.000e+00 0.000e+00 1.256e+03 2.000e+00 4.100e+00]
 [0.000e+00 1.000e+00 1.489e+03 3.000e+00 4.500e+00]
 [0.000e+00 0.000e+00 1.236e+03 3.000e+00 4.900e+00]
 [1.000e+00 0.000e+00 2.311e+03 2.000e+00 5.100e+00]
 [0.000e+00 1.000e+00 2.245e+03 3.000e+00 5.300e+00]
 [0.000e+00 0.000e+00 2.365e+03 1.000e+00 5.90

In [10]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state=8)
model = LinearRegression()
model.fit(x_train, y_train)
result = model.score(x_test, y_test)*100
print(result)

97.65644313582774


In [11]:
print(model.predict(x_test))

[109488.70541796  39303.64764263  56306.97732929  84322.31231461
  72142.88095019  45610.17685718]


In [12]:
print(y_test)

[105582 39343 54445 81363 67938 39891]


In [13]:
print(Y)

[39343 46205 37731 43525 39891 56642 60150 54445 64445 57189 63218 55794
 56957 57081 61111 67938 66029 83088 81363 93940 91738 98273 101302 113812
 109431 105582 116969 112635 122391 121872]


In [18]:
import numpy as np
#Using sample data

new_data = np.array([['Testing',2100,1,1.13], ['Development', 2104, 2, 1.5], ['UX Designer', 2300, 0, 1.1]])
new_data[:,0] = le.fit_transform(new_data[:,0])
new_data = oh.fit_transform(new_data).toarray()
new_data = new_data[:,1:]


/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


TypeError: Wrong type for parameter `n_values`. Expected 'auto', int or array of ints, got <class 'numpy.ndarray'>